[package]
name = "files"
version = "0.1.0"
authors = ["Nicol√°s Vargas Ortega <nvortega92@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
